/* Public, pastor-reviewed selections only. See docs/grow-maintenance.md.
   Leave unconfirmed links, books and weekly passages empty. No credentials here. */
var CREEK_GROW_CONTENT = {
  updated: '2026-09-07',
  series: {
    title: 'Habakkuk',
    subtitle: 'Bringing our questions before God.',
    introduction: 'Over the coming months, we’re walking through Habakkuk—bringing honest questions to God and learning to trust Him as we wait.',
    currentPassage: null,
    nextPassage: { reference: 'Habakkuk 1:2–4', date: '2026-09-20' },
    pause: {
      date: '2026-09-13',
      title: 'Sunday, September 13 · Colossians 3',
      description: 'We’ll return to Colossians 3 this Sunday, then continue Habakkuk with 1:2–4 on Sunday, September 20.'
    }
  },
  spotify: {
    title: 'Songs @ the Creek',
    description: 'Psalms, hymns, and songs of hope. Worship centered on Christ and grounded in Scripture.',
    playlistUrl: 'https://open.spotify.com/playlist/58ciuGp95u3Sq1bWVjSu13'
  },
  books: [
    {
      "id": "lewis-mere-christianity",
      "approved": true,
      "title": "Mere Christianity",
      "subtitle": null,
      "author": "C. S. Lewis",
      "category": "Faith foundations",
      "note": "Builds a reasoned case for Christian belief, then explores Christian character and what it means to live a transformed life.",
      "reader": "Adults exploring Christianity or strengthening their understanding of its central claims",
      "context": "Apologetics drawn from wartime radio talks; broad Christian common ground rather than a Baptist doctrinal handbook.",
      "url": "https://churchsource.com/products/mere-christianity"
    },
    {
      "id": "lewis-screwtape-letters",
      "approved": true,
      "title": "The Screwtape Letters",
      "subtitle": null,
      "author": "C. S. Lewis",
      "category": "Christian imagination",
      "note": "Fictional correspondence between two tempters exposes ordinary spiritual distractions, self-deception, and habits that quietly pull people away from God.",
      "reader": "Adults comfortable with irony and reflective discussion",
      "context": "Satirical fiction told through a devil's unreliable perspective; readers must recognize the deliberate reversal of good and evil.",
      "url": "https://churchsource.com/products/the-screwtape-letters-1"
    },
    {
      "id": "lewis-great-divorce",
      "approved": true,
      "title": "The Great Divorce",
      "subtitle": null,
      "author": "C. S. Lewis",
      "category": "Christian imagination",
      "note": "An imagined journey between hell and heaven explores the stubborn attachments, evasions, and choices that keep people from receiving grace.",
      "reader": "Adults interested in allegory and guided theological conversation",
      "context": "Fable and allegory about judgment and grace; present its imagined afterlife as fiction, not a literal account of heaven and hell.",
      "url": "https://churchsource.com/products/the-great-divorce"
    },
    {
      "id": "tozer-knowledge-holy",
      "approved": true,
      "title": "The Knowledge of the Holy",
      "subtitle": null,
      "author": "A. W. Tozer",
      "category": "Knowing God",
      "note": "Reflects on God's character and majesty, connecting what Christians believe about him with reverence, prayer, worship, and daily life.",
      "reader": "Adults seeking thoughtful devotional reading about God's attributes",
      "context": "Devotional theology focused on God's attributes; a short book suited to slow reflection rather than hurried reading.",
      "url": "https://churchsource.com/products/the-knowledge-of-the-holy"
    },
    {
      "id": "tozer-pursuit-god",
      "approved": true,
      "title": "The Pursuit of God",
      "subtitle": null,
      "author": "A. W. Tozer",
      "category": "Prayer and spiritual growth",
      "note": "Calls readers to seek God wholeheartedly, surrender competing attachments, and cultivate humility, attentive prayer, and awareness of his presence.",
      "reader": "Adults seeking renewed devotion; useful for mentoring conversations",
      "context": "Devotional exhortation with contemplative language; review its treatment of hearing God's voice when planning church discussion.",
      "url": "https://www.moodypublishers.com/the-pursuit-of-god"
    },
    {
      "id": "packer-knowing-god",
      "approved": true,
      "title": "Knowing God",
      "subtitle": null,
      "author": "J. I. Packer",
      "category": "Knowing God",
      "note": "Connects careful study of God's character with personal trust, worship, adoption in Christ, and confidence in his faithfulness through trials.",
      "reader": "Adults ready for sustained theological reading or a guided study group",
      "context": "Substantial devotional theology; current publisher edition is the 50th Anniversary Edition, distinct from its companion study guide and devotional journal.",
      "url": "https://ivpress.com/knowing-god"
    },
    {
      "id": "packer-evangelism-sovereignty",
      "approved": true,
      "title": "Evangelism and the Sovereignty of God",
      "subtitle": null,
      "author": "J. I. Packer",
      "category": "Discipleship and mission",
      "note": "Explains how confidence in God's sovereignty supports evangelism, holding together human responsibility, faithful gospel witness, and dependence on God's work.",
      "reader": "Deacons, teachers, ministry leaders, and adults asking how sovereignty relates to sharing the gospel",
      "context": "Focused theological argument on divine sovereignty and human responsibility; a discussion candidate rather than a step-by-step outreach workbook.",
      "url": "https://www.ivpress.com/evangelism-and-the-sovereignty-of-god"
    },
    {
      "id": "sproul-holiness-god",
      "approved": true,
      "title": "The Holiness of God",
      "subtitle": null,
      "author": "R. C. Sproul",
      "category": "Knowing God",
      "note": "Explores God's holiness and the human response to it, inviting deeper reverence, renewed worship, and a life shaped by his character.",
      "reader": "Adults beginning doctrinal study or seeking a deeper understanding of holiness",
      "context": "Theology for general readers using biblical encounters with God's holiness; choose the book, not the separate teaching series with the same title.",
      "url": "https://store.ligonier.org/the-holiness-of-god-paperback"
    },
    {
      "id": "sproul-essential-truths",
      "approved": true,
      "title": "Essential Truths of the Christian Faith",
      "subtitle": null,
      "author": "R. C. Sproul",
      "category": "Faith foundations",
      "note": "Introduces more than one hundred Christian doctrines through concise explanations and familiar illustrations, providing a reference for growing theological understanding.",
      "reader": "Adults and teachers wanting a topical doctrine reference",
      "context": "A topical theological reference rather than a continuous narrative; review individual doctrinal entries for fit with Bluff Creek's teaching.",
      "url": "https://www.tyndale.com/p/essential-truths-of-the-christian-faith/9780842320016"
    },
    {
      "id": "platt-radical",
      "approved": true,
      "title": "Radical",
      "subtitle": "Taking Back Your Faith from the American Dream",
      "author": "David Platt",
      "category": "Discipleship and mission",
      "note": "Challenges comfortable Christianity through Jesus’ call to costly discipleship, connecting everyday choices with generosity, mission, and obedience.",
      "reader": "Adults and older teens considering discipleship and mission",
      "context": "An exhortation to examine priorities, including a yearlong practical response; useful for a discussion group.",
      "url": "https://penguinrandomhouselibrary.com/book/?isbn=9781601422217",
      "edition": "2010 paperback"
    },
    {
      "id": "platt-follow-me",
      "approved": true,
      "title": "Follow Me",
      "subtitle": "A Call to Die. A Call to Live.",
      "author": "David Platt",
      "category": "Discipleship and mission",
      "note": "Examines Jesus’ invitation to follow him, emphasizing transformed allegiance, obedience, evangelism, and the difference between cultural identity and discipleship.",
      "reader": "Adults exploring what Christian discipleship means",
      "context": "A direct challenge about conversion and discipleship; the publisher provides a discussion guide.",
      "url": "https://www.tyndale.com/p/follow-me/9781414373287",
      "edition": "2013 softcover"
    },
    {
      "id": "piper-desiring-god",
      "approved": true,
      "title": "Desiring God",
      "subtitle": "Meditations of a Christian Hedonist",
      "author": "John Piper",
      "category": "Knowing God and spiritual growth",
      "note": "Develops Piper’s argument that delight in God and glorifying God belong together, applying that conviction to the Christian life.",
      "reader": "Readers wanting sustained theological reflection",
      "context": "Introduces Piper’s particular framework of Christian Hedonism; a longer theological treatment than his shorter devotional works.",
      "url": "https://www.desiringgod.org/books/desiring-god",
      "edition": "Revised edition, 2025 hardcover"
    },
    {
      "id": "piper-dont-waste",
      "approved": true,
      "title": "Don’t Waste Your Life",
      "subtitle": null,
      "author": "John Piper",
      "category": "Purpose and Christian living",
      "note": "Urges readers to place Christ’s glory above comfort and achievement, pursuing a purposeful life of sacrificial love and eternal significance.",
      "reader": "Older teens, young adults, and adults rethinking priorities",
      "context": "Written with the next generation especially in view; treats vocation, risk, and sacrifice through Piper’s joy-in-God emphasis.",
      "url": "https://www.desiringgod.org/books/dont-waste-your-life",
      "edition": "2010 edition listed by the author’s ministry"
    },
    {
      "id": "piper-seeing-savoring",
      "approved": true,
      "title": "Seeing and Savoring Jesus Christ",
      "subtitle": null,
      "author": "John Piper",
      "category": "Jesus and devotional reading",
      "note": "Invites readers to contemplate the biblical portrait of Jesus, seeking deeper understanding of his character and greater delight in him.",
      "reader": "Newer readers and believers seeking Christ-focused reflection",
      "context": "A shorter introduction to Piper centered on the person of Christ, rather than a systematic theology.",
      "url": "https://www.desiringgod.org/books/seeing-and-savoring-jesus-christ",
      "edition": "Revised edition, 2004 paperback"
    },
    {
      "id": "permenter-spiritual-operators-manual",
      "approved": true,
      "title": "The Spiritual Operator’s Manual",
      "subtitle": "The C.O.V.E.N.A.N.T. Method for Text-Driven, Christ-Exalting, Mission-Ready Preaching",
      "author": "Cole Permenter",
      "category": "Bible study and teaching",
      "note": "Teaches a repeatable process for interpreting Scripture faithfully and shaping Christ-centered lessons, preaching, and everyday application.",
      "reader": "Bible teachers, small-group leaders, pastors, and serious Bible readers",
      "context": "A method guide for studying and teaching Scripture. The linked author page offers the digital edition; check formats there.",
      "url": "https://www.base1520.com/spiritual-operators-manual/",
      "edition": "Digital edition; author page checked September 7, 2026"
    },
    {
      "id": "gallaty-growing-up",
      "approved": true,
      "title": "Growing Up",
      "subtitle": "How to Be a Disciple Who Makes Disciples",
      "author": "Robby Gallaty",
      "category": "Discipleship and group leadership",
      "note": "Offers a practical approach to spiritual growth through discipleship groups, helping believers develop habits and guide others toward maturity.",
      "reader": "New disciples, mentors, and small-group leaders",
      "context": "Uses Gallaty’s D-Group model; select the revised and updated edition when linking a purchase.",
      "url": "https://www.bhpublishinggroup.com/product/growing-up-revised-and-updated-2/",
      "edition": "Revised and Updated, 2022"
    },
    {
      "id": "gallaty-rediscovering",
      "approved": true,
      "title": "Rediscovering Discipleship",
      "subtitle": "Making Jesus’ Final Words Our First Work",
      "author": "Robby Gallaty",
      "category": "Discipleship and group leadership",
      "note": "Combines historical examples with practical guidance for overcoming obstacles to disciple making and building relationships that help others grow.",
      "reader": "Deacons, teachers, ministry leaders, and prospective mentors",
      "context": "Offers ministry history and a step-by-step model for multiplying disciples; useful for leader preparation.",
      "url": "https://zondervanacademic.com/products/rediscovering-discipleship",
      "edition": "2015 softcover"
    },
    {
      "id": "merida-love-your-church",
      "approved": true,
      "title": "Love Your Church",
      "subtitle": "8 Great Things About Being a Church Member",
      "author": "Tony Merida",
      "category": "Church life",
      "note": "Explores belonging, hospitality, service, care, and mission as practical ways ordinary members can participate in the life of their church.",
      "reader": "New members, church members, and small groups",
      "context": "Includes a discussion guide and publisher-provided group resources. Ray Ortlund wrote the foreword; he is not a coauthor.",
      "url": "https://www.thegoodbook.com/ministry/love-your-church",
      "edition": "2021 paperback"
    },
    {
      "id": "merida-ordinary",
      "approved": true,
      "title": "Ordinary",
      "subtitle": "How to Turn the World Upside Down",
      "author": "Tony Merida",
      "category": "Christian living and service",
      "note": "Connects everyday Christian faithfulness with hospitality, care for vulnerable neighbors, humble service, and sharing the gospel in ordinary relationships.",
      "reader": "Church members and ministry volunteers",
      "context": "Select the trade book with this subtitle. Lifeway also sells a distinct Ordinary Bible Study Book with different content and ISBN.",
      "url": "https://www.lifeway.com/en/product/ebook-ordinary-P005665762",
      "edition": "2015 eBook listing; trade book, not the separate Bible study workbook"
    },
    {
      "id": "fee-stuart-all-its-worth",
      "approved": true,
      "title": "How to Read the Bible for All Its Worth",
      "subtitle": null,
      "author": "Gordon D. Fee and Douglas Stuart",
      "category": "Bible study tools",
      "note": "Introduces interpretation through biblical genres, helping readers consider original context before applying passages to Christian life today.",
      "reader": "Growing Bible readers, teachers, and study leaders",
      "context": "A guide to reading genres and interpreting Scripture, not a devotional. The fourth-edition publisher listing has no separate subtitle.",
      "url": "https://zondervanacademic.com/products/how-to-read-the-bible-for-all-its-worth-4th",
      "edition": "Fourth Edition (2014)"
    },
    {
      "id": "fee-stuart-book-by-book",
      "approved": true,
      "title": "How to Read the Bible Book by Book",
      "subtitle": "A Guided Tour",
      "author": "Gordon D. Fee and Douglas Stuart",
      "category": "Bible background and overview",
      "note": "Provides background, structure, and reading guidance for each biblical book, helping readers follow its message within Scripture’s larger story.",
      "reader": "Bible readers wanting context and Sunday school teachers",
      "context": "A reading companion covering all 66 books, including Habakkuk. It supplies book context rather than a full verse-by-verse commentary. Audiobook narrator Trevor Thompson is not a print-book coauthor.",
      "url": "https://zondervanacademic.com/products/how-to-read-the-bible-book-by-book",
      "edition": "2014 softcover publisher listing"
    }
  ]
};
