(function(root){
  'use strict';
  function sheetLink(value){try{var u=new URL(value);return u.protocol==='https:' && u.hostname==='docs.google.com' && !u.username && !u.password && /^\/spreadsheets\/d\/[A-Za-z0-9_-]+\/(?:edit)?$/.test(u.pathname)?u.origin+u.pathname:null}catch(_){return null}}
  function create(options){
    var host=options.root,doc=host.ownerDocument,rows=[],loadId=0,selected='',previewURL=null,dialog=null,requestId=0,failed=false;
    host.innerHTML='<div class="panel membership-intro"><p class="eyebrow">The membership archive</p><h2>Every name has a story.</h2><p>Keep the original pages, preserve uncertain dates, and follow each person’s history through the life of the church.</p><p id="membership-sheet-note" class="membership-note">The existing Google ledger remains your working source while its private connection is being prepared. Changes in Creek Office do not yet write back to Google Sheets.</p><a id="membership-sheet-link" target="_blank" rel="noopener noreferrer" hidden>Open the duplicated Google ledger ↗</a></div><div class="membership-controls"><select id="membership-person" aria-label="Choose a person’s history"><option value="">All people</option></select><input id="membership-search" type="search" placeholder="Search history, dates or source pages" aria-label="Search membership history"><button id="membership-add" type="button">Add history / page photo</button></div><p class="membership-note" id="membership-status" role="status"></p><div class="panel membership-history" id="membership-history"></div>';
    var find=function(id){return host.querySelector('#'+id)};
    var ledger=sheetLink(options.sheetUrl);if(ledger){find('membership-sheet-link').href=ledger;find('membership-sheet-link').hidden=false}
    function context(){return options.getContext()}
    function active(epoch){return options.isCurrent(epoch)&&context().canEdit}
    function check(epoch){if(!active(epoch))throw new Error('Your session changed. Sign in again before saving.')}
    function name(person){return [person.last_name,person.first_name,person.middle_name].filter(Boolean).join(', ')}
    function peopleOptions(select,placeholder){var value=select.value;select.replaceChildren(new Option(placeholder,''));options.people().forEach(function(p){select.add(new Option(name(p)+(p.membership_number?' · #'+p.membership_number:''),p.id))});select.value=value}
    function closeDialog(){requestId++;if(previewURL){URL.revokeObjectURL(previewURL);previewURL=null}if(dialog){if(dialog.open)dialog.close();dialog.remove();dialog=null}}
    function clear(){loadId++;rows=[];selected='';failed=false;closeDialog();find('membership-person').replaceChildren(new Option('All people',''));find('membership-search').value='';find('membership-history').replaceChildren();find('membership-status').textContent=''}
    async function load(epoch){
      if(!active(epoch)){clear();return}var currentLoad=++loadId,all=[];failed=false;
      try{for(var offset=0;;offset+=1000){var query=options.db.from('membership_history').select('*').order('created_at',{ascending:false}).order('id',{ascending:true});var result=typeof query.range==='function'?await query.range(offset,offset+999):await query;
        if(!active(epoch)||currentLoad!==loadId)return;if(result.error)throw result.error;all=all.concat(result.data||[]);if(!result.data||result.data.length<1000||typeof query.range!=='function')break;
      }rows=all;render()}catch(_){if(active(epoch)&&currentLoad===loadId){rows=[];failed=true;render();find('membership-status').textContent='History could not load. The private membership migration and connection must be ready before saving.'}}
    }
    function render(){
      if(!context().canEdit)return;peopleOptions(find('membership-person'),'All people');if(selected)find('membership-person').value=selected;
      var person=find('membership-person').value,term=find('membership-search').value.trim().toLowerCase(),people=new Map(options.people().map(function(p){return[p.id,p]}));
      var filtered=rows.filter(function(r){return(!person||r.contact_id===person)&&(!term||[name(people.get(r.contact_id)||{}),r.event_type,r.event_date,r.date_text,r.details,r.source_label].join(' ').toLowerCase().includes(term))});
      var area=find('membership-history');area.replaceChildren();find('membership-add').disabled=failed;
      find('membership-status').textContent=filtered.length+' history entries'+(filtered.length>100?' · showing the first 100; narrow the search to see more':'')+'. Corrections keep the original entry.';
      if(!filtered.length){var blank=doc.createElement('p');blank.className='membership-blank';blank.textContent=failed?'History is unavailable.':'No history entries match. Add a verified entry or a photographed source page to begin.';area.appendChild(blank)}
      filtered.slice(0,100).forEach(function(r){var a=doc.createElement('article');a.className='membership-entry';var owner=doc.createElement('small');owner.textContent=name(people.get(r.contact_id)||{})||'Member record';a.appendChild(owner);var title=doc.createElement('h3');title.textContent=r.event_type+' · '+(r.date_text||r.event_date||'Date not yet confirmed');a.appendChild(title);if(r.details){var body=doc.createElement('p');body.textContent=r.details;a.appendChild(body)}var source=doc.createElement('small');source.textContent='Source: '+(r.source_label||'Not recorded')+(r.corrects_id?' · Correction to an earlier entry':'');a.appendChild(source);
        if(r.source_document_id){var original=doc.createElement('button');original.className='quiet';original.textContent='Open original page';original.onclick=function(){openSource(r.source_document_id)};a.appendChild(original)}
        var correction=doc.createElement('button');correction.className='quiet';correction.textContent='Add correction';correction.onclick=function(){openForm(r)};a.appendChild(correction);area.appendChild(a)});
    }
    async function openSource(id){var epoch=context().epoch;closeDialog();var req=requestId;dialog=doc.createElement('dialog');dialog.className='membership-dialog';dialog.setAttribute('aria-label','Original membership page');var title=doc.createElement('h2');title.textContent='Original page';var resultNode=doc.createElement('p');resultNode.textContent='Preparing a private link…';var close=doc.createElement('button');close.textContent='Close';close.onclick=closeDialog;dialog.append(title,resultNode,close);doc.body.appendChild(dialog);dialog.addEventListener('cancel',function(e){e.preventDefault();closeDialog()});dialog.showModal();
      try{var record=await options.db.from('documents').select('storage_path').eq('id',id).maybeSingle();if(!active(epoch)||req!==requestId)return;if(record.error||!record.data)throw new Error();var signed=await options.db.storage.from('church-documents').createSignedUrl(record.data.storage_path,60);if(!active(epoch)||req!==requestId)return;if(signed.error)throw new Error();var url=new URL(signed.data.signedUrl);if(url.protocol!=='https:')throw new Error();var link=doc.createElement('a');link.href=url.href;link.target='_blank';link.rel='noopener noreferrer';link.textContent='Open the original page (link expires in one minute)';resultNode.replaceChildren(link);doc.defaultView.setTimeout(function(){if(req===requestId&&dialog)resultNode.textContent='This link has expired. Close and reopen for a fresh link.'},60000)}catch(_){if(active(epoch)&&req===requestId)resultNode.textContent='Could not open the private source page. Try again after checking access.'}}
    function openForm(correction){if(!context().canEdit||failed)return;closeDialog();var epoch=context().epoch,formRequest=requestId;dialog=doc.createElement('dialog');dialog.className='membership-dialog';dialog.setAttribute('aria-labelledby','history-form-title');dialog.innerHTML='<header><div><p class="eyebrow">Preserve the record</p><h2 id="history-form-title">'+(correction?'Add a correction':'Add history or a page photo')+'</h2></div><button type="button" class="quiet" data-close>Close</button></header><p class="membership-note">Keep uncertain handwriting exactly as it appears, using [unclear] where needed. Review the transcription against the page before saving. A page photo is not automatically transcribed here.</p><form><div class="form-grid"><label class="wide">Person<select name="contact_id" required></select></label><label>Event or record type<input name="event_type" required maxlength="160" placeholder="Baptism, joined by letter, dismissal…"></label><label>Verified date (optional)<input name="event_date" type="date"></label><label class="wide">Date as written / approximate date<input name="date_text" maxlength="500" placeholder="e.g. Summer 1964; day unclear"></label><label class="wide">Source / book and page<input name="source_label" required maxlength="500" placeholder="Membership book, page number"></label><label class="wide">Transcription and historical details<textarea name="details" maxlength="10000" placeholder="Preserve the original wording. Mark uncertain letters or dates."></textarea></label><label class="wide">Existing source document (optional)<select name="existing_source"><option value="">No existing document</option></select></label><label class="wide">Original page photo (optional)<input name="page" type="file" accept="image/jpeg,image/png,image/webp" capture="environment"><span class="membership-note">JPEG, PNG or WebP · up to 15 MB. For a new person, add their People record first.</span></label></div><img class="page-preview" alt="Selected original page for transcription review" hidden><label class="review-check"><input name="reviewed" type="checkbox" required><span>I checked this entry against its source and marked anything uncertain.</span></label><output role="alert"></output><footer><button class="quiet" type="button" data-close>Cancel</button><button type="submit">Save reviewed history</button></footer></form>';
      var form=dialog.querySelector('form'),select=form.elements.contact_id;var existing=form.elements.existing_source;(options.documents?options.documents():[]).forEach(function(d){existing.add(new Option(d.title,d.id))});if(correction&&correction.source_document_id){if(!Array.from(existing.options).some(function(o){return o.value===correction.source_document_id}))existing.add(new Option('Original source for this entry',correction.source_document_id));existing.value=correction.source_document_id;}peopleOptions(select,'Choose a person');select.value=correction?correction.contact_id:find('membership-person').value;if(correction){select.disabled=true;['event_type','event_date','date_text','source_label','details'].forEach(function(k){form.elements[k].value=correction[k]||''})}
      dialog.querySelectorAll('[data-close]').forEach(function(b){b.onclick=closeDialog});dialog.addEventListener('cancel',function(e){e.preventDefault();closeDialog()});
      form.elements.page.onchange=function(){if(previewURL)URL.revokeObjectURL(previewURL);previewURL=null;var img=dialog.querySelector('img'),file=form.elements.page.files[0];img.hidden=true;img.removeAttribute('src');if(file&&['image/jpeg','image/png','image/webp'].includes(file.type)&&file.size<=15728640){previewURL=URL.createObjectURL(file);img.src=previewURL;img.hidden=false}};
      form.onsubmit=async function(e){e.preventDefault();if(!form.reportValidity())return;var save=form.querySelector('[type=submit]');if(save.disabled)return;save.disabled=true;var output=form.querySelector('output');output.textContent='';var sourceId=form.elements.existing_source.value||null,uploadedPath=null,createdDoc=null;function checkForm(){check(epoch);if(formRequest!==requestId)throw new Error('This review was closed before it finished.')}
        try{checkForm();var personId=correction?correction.contact_id:select.value;if(!options.people().some(function(p){return p.id===personId}))throw new Error('Choose a current person record.');var eventType=form.elements.event_type.value.trim(),source=form.elements.source_label.value.trim();if(!eventType||!source)throw new Error('Enter an event type and source.');var file=form.elements.page.files[0];
          if(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||!file.size||file.size>15728640)throw new Error('Choose a JPEG, PNG or WebP image up to 15 MB.');var suffix={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type];uploadedPath=context().userId+'/membership-history/'+crypto.randomUUID()+'.'+suffix;var uploaded=await options.db.storage.from('church-documents').upload(uploadedPath,file,{contentType:file.type,upsert:false});checkForm();if(uploaded.error)throw new Error('The page upload failed. No history was saved.');var metadata=await options.db.from('documents').insert({title:'Membership source · '+source,category:'other',description:'Original membership source page. Retain with historical records.',storage_path:uploadedPath,file_name:'membership-source.'+suffix,mime_type:file.type,size_bytes:file.size,uploaded_by:context().userId}).select('id').single();checkForm();if(metadata.error)throw new Error('The source could not be filed. No history was saved.');createdDoc=metadata.data.id;sourceId=createdDoc}
          checkForm();var result=await options.db.from('membership_history').insert({contact_id:personId,event_type:eventType,event_date:form.elements.event_date.value||null,date_text:form.elements.date_text.value.trim()||null,details:form.elements.details.value.trim()||null,source_label:source,source_document_id:sourceId||null,corrects_id:correction?correction.id:null});check(epoch);if(result.error)throw new Error('History could not be saved. Check staff access and try again.');if(formRequest!==requestId)return;closeDialog();await options.refresh();if(active(epoch))options.notice('Reviewed history saved. The Google ledger has not been changed.');
        }catch(error){if(active(epoch)&&formRequest===requestId){output.textContent=error.message+(createdDoc?' The uploaded source is retained in Documents; use it when retrying.':'');if(createdDoc){existing.add(new Option('Uploaded source · '+source,createdDoc));existing.value=createdDoc;form.elements.page.value='';} }}
        finally{if(active(epoch)&&formRequest===requestId)save.disabled=false}
      };doc.body.appendChild(dialog);dialog.showModal();
    }
    find('membership-person').onchange=function(){selected=find('membership-person').value;render()};find('membership-search').oninput=render;find('membership-add').onclick=function(){openForm()};
    return{load:load,render:render,clear:clear,selectPerson:function(id){selected=id;find('membership-person').value=id;render();location.hash='history'}};
  }
  root.CreekMembership={create:create,sheetLink:sheetLink};
}(typeof window!=='undefined'?window:globalThis));
