-- Proposed only. Generated by Supabase CLI; no active migration is changed.
-- Explicit notification bindings do not edit a care plan, staff role or account.
begin;

create table private.care_reminder_settings (
 id boolean primary key default true check(id),
 enabled boolean not null default false,
 pastor_user_ids uuid[] not null default '{}',
 version integer not null default 1 check(version>0),
 updated_at timestamptz not null default now(),
 updated_by uuid references auth.users(id) on delete restrict,
 check(cardinality(pastor_user_ids)<=20 and array_position(pastor_user_ids,null) is null)
);
insert into private.care_reminder_settings(id) values(true);

create table private.care_reminder_bindings (
 source_type text not null check(source_type in('guest_task','care_plan')),
 source_id uuid not null,
 owner_user_id uuid references auth.users(id) on delete restrict,
 enabled boolean not null default false,
 cycle_id uuid not null default gen_random_uuid(),
 version integer not null default 1 check(version>0),
 approved_source_version integer not null check(approved_source_version>0),
 lifecycle_version integer,
 linked_guest_task_id uuid references public.app_submission_tasks(id) on delete restrict,
 created_at timestamptz not null default now(),
 created_by uuid not null references auth.users(id) on delete restrict,
 updated_at timestamptz not null default now(),
 updated_by uuid not null references auth.users(id) on delete restrict,
 primary key(source_type,source_id),
 check((source_type='guest_task' and lifecycle_version is not null and lifecycle_version>0 and linked_guest_task_id is null)
    or (source_type='care_plan' and lifecycle_version is null))
);
create table private.care_reminder_config_receipts (
 actor_id uuid not null references auth.users(id) on delete restrict,
 request_id uuid not null,
 operation text not null check(operation in('settings','binding')),
 payload jsonb not null,
 result jsonb not null,
 created_at timestamptz not null default now(),
 primary key(actor_id,request_id)
);
alter table private.care_reminder_settings enable row level security;
alter table private.care_reminder_bindings enable row level security;
alter table private.care_reminder_config_receipts enable row level security;
revoke all on private.care_reminder_settings,private.care_reminder_bindings,private.care_reminder_config_receipts from public,anon,authenticated,service_role;

create function private.keep_care_reminder_config_receipt()
returns trigger language plpgsql security invoker set search_path='' as $$
begin raise exception 'CARE_REMINDER_RECEIPT_IMMUTABLE' using errcode='55000';end $$;
create trigger care_reminder_receipt_preserved before update or delete on private.care_reminder_config_receipts
for each row execute function private.keep_care_reminder_config_receipt();

create function private.set_care_reminder_settings(p_request_id uuid,p_version integer,p_enabled boolean,p_pastor_user_ids uuid[])
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_row private.care_reminder_settings%rowtype;v_ids uuid[];v_payload jsonb;v_result jsonb;v_receipt private.care_reminder_config_receipts%rowtype;
begin
 if private.current_staff_role() is distinct from 'admin'::public.staff_role then raise exception 'CARE_REMINDER_ADMIN_REQUIRED' using errcode='42501';end if;
 if p_request_id is null or p_version is null or p_version<1 or p_enabled is null or p_pastor_user_ids is null
  or cardinality(p_pastor_user_ids)>20 or array_position(p_pastor_user_ids,null) is not null then raise exception 'CARE_REMINDER_CONFIG_INVALID' using errcode='22023';end if;
 select coalesce(array_agg(distinct u order by u),'{}'::uuid[]) into v_ids from unnest(p_pastor_user_ids) u;
 if cardinality(v_ids)<>cardinality(p_pastor_user_ids) or (p_enabled and cardinality(v_ids)=0) then raise exception 'CARE_REMINDER_CONFIG_INVALID' using errcode='22023';end if;
 v_payload:=jsonb_build_object('version',p_version,'enabled',p_enabled,'pastor_user_ids',v_ids);
 select * into v_row from private.care_reminder_settings where id for update;
 if not found then raise exception 'CARE_REMINDER_SETTINGS_MISSING' using errcode='55000';end if;
 select * into v_receipt from private.care_reminder_config_receipts where actor_id=auth.uid() and request_id=p_request_id;
 if found then
  if v_receipt.operation<>'settings' or v_receipt.payload is distinct from v_payload then raise exception 'CARE_REMINDER_REQUEST_CONFLICT' using errcode='40001';end if;
  return v_receipt.result;
 end if;
 if v_row.version<>p_version then raise exception 'CARE_REMINDER_VERSION_CONFLICT' using errcode='40001';end if;
 if exists(select 1 from unnest(v_ids) u where not exists(select 1 from private.eligible_intake_staff() s where s.id=u)) then raise exception 'CARE_REMINDER_RECIPIENT_INVALID' using errcode='22023';end if;
 update private.care_reminder_settings set enabled=p_enabled,pastor_user_ids=v_ids,version=version+1,updated_at=clock_timestamp(),updated_by=auth.uid() where id returning * into v_row;
 v_result:=jsonb_build_object('version',v_row.version,'enabled',v_row.enabled,'pastor_user_ids',v_row.pastor_user_ids);
 insert into private.care_reminder_config_receipts(actor_id,request_id,operation,payload,result) values(auth.uid(),p_request_id,'settings',v_payload,v_result);
 return v_result;
end $$;

create function private.set_care_reminder_binding(p_request_id uuid,p_source_type text,p_source_id uuid,p_version integer,
 p_source_version integer,p_owner_user_id uuid,p_enabled boolean,p_restart_cycle boolean,p_lifecycle_version integer,p_linked_guest_task_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_row private.care_reminder_bindings%rowtype;v_task public.app_submission_tasks%rowtype;v_guest public.app_connections%rowtype;
 v_plan public.care_assignments%rowtype;v_payload jsonb;v_result jsonb;v_exists boolean;v_cycle uuid;v_receipt private.care_reminder_config_receipts%rowtype;
begin
 if private.current_staff_role() is distinct from 'admin'::public.staff_role then raise exception 'CARE_REMINDER_ADMIN_REQUIRED' using errcode='42501';end if;
 if p_request_id is null or p_source_type is null or p_source_type not in('guest_task','care_plan') or p_source_id is null
  or p_version is null or p_version<0 or p_source_version is null or p_source_version<1 or p_enabled is null or p_restart_cycle is null
  or (p_source_type='guest_task' and (p_lifecycle_version is null or p_lifecycle_version<1 or p_linked_guest_task_id is not null))
  or (p_source_type='care_plan' and p_lifecycle_version is not null) then raise exception 'CARE_REMINDER_BINDING_INVALID' using errcode='22023';end if;
 v_payload:=jsonb_build_object('source_type',p_source_type,'source_id',p_source_id,'version',p_version,'source_version',p_source_version,
  'owner_user_id',p_owner_user_id,'enabled',p_enabled,'restart_cycle',p_restart_cycle,'lifecycle_version',p_lifecycle_version,'linked_guest_task_id',p_linked_guest_task_id);
 perform id from private.care_reminder_settings where id for update;
 if not found then raise exception 'CARE_REMINDER_SETTINGS_MISSING' using errcode='55000';end if;
 select * into v_receipt from private.care_reminder_config_receipts where actor_id=auth.uid() and request_id=p_request_id;
 if found then
  if v_receipt.operation<>'binding' or v_receipt.payload is distinct from v_payload then raise exception 'CARE_REMINDER_REQUEST_CONFLICT' using errcode='40001';end if;
  return v_receipt.result;
 end if;
 select * into v_row from private.care_reminder_bindings where source_type=p_source_type and source_id=p_source_id for update;
 v_exists:=found;
 if (v_exists and v_row.version<>p_version) or (not v_exists and p_version<>0) then raise exception 'CARE_REMINDER_VERSION_CONFLICT' using errcode='40001';end if;
 if not v_exists and (select count(*) from private.care_reminder_bindings)>=5000 then raise exception 'CARE_REMINDER_SOURCE_LIMIT' using errcode='54000';end if;
 if p_owner_user_id is not null and not exists(select 1 from private.eligible_intake_staff() s where s.id=p_owner_user_id) then raise exception 'CARE_REMINDER_RECIPIENT_INVALID' using errcode='22023';end if;
 -- NOWAIT avoids cycles with existing guest removal/worker source locks.
 begin
  if p_source_type='guest_task' then
   select * into v_task from public.app_submission_tasks where id=p_source_id and kind='guest_followup' for no key update nowait;
   if not found then raise exception 'CARE_REMINDER_SOURCE_MISSING' using errcode='P0002';end if;
   select * into v_guest from public.app_connections where id=v_task.registration_id for no key update nowait;
   if not found then raise exception 'CARE_REMINDER_SOURCE_MISSING' using errcode='P0002';end if;
   if v_task.version<>p_source_version or v_guest.guest_lifecycle_version<>p_lifecycle_version then raise exception 'CARE_REMINDER_SOURCE_CHANGED' using errcode='40001';end if;
   if v_task.guest_removed_at is not null or v_guest.guest_removed_at is not null or v_guest.status='archived' then raise exception 'CARE_REMINDER_SOURCE_INACTIVE' using errcode='22023';end if;
   if p_owner_user_id is distinct from v_task.assigned_staff_user_id then raise exception 'CARE_REMINDER_OWNER_CHANGED' using errcode='40001';end if;
   if v_exists and v_row.lifecycle_version<>p_lifecycle_version and not p_restart_cycle then raise exception 'CARE_REMINDER_RESTART_REQUIRED' using errcode='40001';end if;
  else
   select * into v_plan from public.care_assignments where id=p_source_id for no key update nowait;
   if not found then raise exception 'CARE_REMINDER_SOURCE_MISSING' using errcode='P0002';end if;
   if v_plan.version<>p_source_version then raise exception 'CARE_REMINDER_SOURCE_CHANGED' using errcode='40001';end if;
   if p_linked_guest_task_id is not null and (not v_plan.one_time or v_plan.care_role<>'welcome' or not exists(
    select 1 from public.app_submission_tasks t join public.app_connections c on c.id=t.registration_id
    where t.id=p_linked_guest_task_id and t.kind='guest_followup' and c.contact_id=v_plan.contact_id)) then raise exception 'CARE_REMINDER_LINK_INVALID' using errcode='22023';end if;
  end if;
 exception when lock_not_available then raise exception 'CARE_REMINDER_SOURCE_BUSY' using errcode='55P03';end;
 v_cycle:=case when not v_exists or p_restart_cycle then gen_random_uuid() else v_row.cycle_id end;
 insert into private.care_reminder_bindings(source_type,source_id,owner_user_id,enabled,cycle_id,approved_source_version,lifecycle_version,linked_guest_task_id,created_by,updated_by)
 values(p_source_type,p_source_id,p_owner_user_id,p_enabled,v_cycle,p_source_version,p_lifecycle_version,p_linked_guest_task_id,auth.uid(),auth.uid())
 on conflict(source_type,source_id) do update set owner_user_id=excluded.owner_user_id,enabled=excluded.enabled,cycle_id=excluded.cycle_id,
  approved_source_version=excluded.approved_source_version,lifecycle_version=excluded.lifecycle_version,linked_guest_task_id=excluded.linked_guest_task_id,
  version=care_reminder_bindings.version+1,updated_at=clock_timestamp(),updated_by=auth.uid() returning * into v_row;
 v_result:=jsonb_build_object('source_type',v_row.source_type,'source_id',v_row.source_id,'version',v_row.version,'cycle_id',v_row.cycle_id,'enabled',v_row.enabled,'lifecycle_version',v_row.lifecycle_version);
 insert into private.care_reminder_config_receipts(actor_id,request_id,operation,payload,result) values(auth.uid(),p_request_id,'binding',v_payload,v_result);
 return v_result;
end $$;

-- Internal projection only: no direct client/service grant. A reviewed queue
-- definer may call it while holding the reminder settings lock. This is a
-- statement snapshot, not a lock held across external delivery.
create function private.care_reminder_source_rows(p_today date)
returns table(source_type text,source_id uuid,cycle_id uuid,due_on date,state text,owner_user_id uuid,source_fingerprint text)
language plpgsql stable security invoker set search_path='' as $$
begin
 if p_today is null or p_today<'0001-01-01'::date or p_today>'9999-12-31'::date then raise exception 'CARE_REMINDER_DATE_INVALID' using errcode='22023';end if;
 if not exists(select 1 from private.care_reminder_settings where id) then raise exception 'CARE_REMINDER_SETTINGS_MISSING' using errcode='55000';end if;
 if (select count(*) from private.care_reminder_bindings)>5000 then raise exception 'CARE_REMINDER_SOURCE_LIMIT' using errcode='54000';end if;
 return query
 with care as (
  select b.source_type,b.source_id,b.cycle_id,b.owner_user_id,b.version binding_version,p.version source_version,
   p.care_role,p.started_on,p.first_due_on,p.cadence_days,p.cadence_months,p.one_time,c.status person_status,
   h.success_on,s.next_contact_on,hist.fingerprint_visits
  from private.care_reminder_bindings b join public.care_assignments p on b.source_type='care_plan' and p.id=b.source_id
  join public.contacts c on c.id=p.contact_id
  left join lateral (select v.contacted_on success_on from public.care_visits v
   where v.contact_id=p.contact_id and v.care_role=p.care_role and v.contacted_on<=p_today and (not p.one_time or v.contacted_on>=p.started_on) and v.outcome='contacted'
   order by v.contacted_on desc,v.created_at desc,v.id desc limit 1) h on true
  left join lateral (select v.next_contact_on from public.care_visits v
   where v.contact_id=p.contact_id and v.care_role=p.care_role and v.contacted_on<=p_today and (not p.one_time or v.contacted_on>=p.started_on)
    and (v.outcome='contacted' or v.next_contact_on is not null)
   order by v.contacted_on desc,v.created_at desc,v.id desc limit 1) s on true
  left join lateral (select coalesce(jsonb_agg(jsonb_build_array(v.id,v.contacted_on,v.outcome,v.next_contact_on,v.created_at) order by v.id),'[]'::jsonb) fingerprint_visits
   from public.care_visits v where v.contact_id=p.contact_id and v.care_role=p.care_role) hist on true
  where b.enabled and not p.paused and c.status in('active','visitor') and not(p.one_time and h.success_on is not null)
   and not(p.one_time and p.care_role='welcome' and exists(select 1 from public.app_submission_tasks linked
    join public.app_connections registration on registration.id=linked.registration_id
    where linked.id=b.linked_guest_task_id and linked.kind='guest_followup' and registration.contact_id=p.contact_id))
 ), normalized_care as (
  select k.*,coalesce(k.next_contact_on,case when k.success_on is null then k.first_due_on end,
   case when k.cadence_months is not null then (coalesce(k.success_on,k.started_on)+make_interval(months=>k.cadence_months))::date
    else coalesce(k.success_on,k.started_on)+k.cadence_days end) calculated_due from care k
 ), guest as (
  select b.source_type,b.source_id,b.cycle_id,b.owner_user_id,b.version binding_version,t.version source_version,t.due_on,c.guest_lifecycle_version
  from private.care_reminder_bindings b join public.app_submission_tasks t on b.source_type='guest_task' and t.id=b.source_id and t.kind='guest_followup'
  join public.app_connections c on c.id=t.registration_id
  where b.enabled and t.status<>'completed' and t.guest_removed_at is null and c.guest_removed_at is null and c.status<>'archived'
   and b.lifecycle_version=c.guest_lifecycle_version and b.owner_user_id is not distinct from t.assigned_staff_user_id
 )
 select k.source_type,k.source_id,k.cycle_id,k.calculated_due,'open'::text,k.owner_user_id,
  encode(sha256(convert_to(jsonb_build_array(k.source_type,k.source_id,k.cycle_id,k.owner_user_id,k.binding_version,k.source_version,k.calculated_due,
   k.care_role,k.started_on,k.first_due_on,k.cadence_days,k.cadence_months,k.one_time,k.person_status,k.fingerprint_visits)::text,'UTF8')),'hex')
 from normalized_care k
 union all
 select g.source_type,g.source_id,g.cycle_id,g.due_on,'open'::text,g.owner_user_id,
  encode(sha256(convert_to(jsonb_build_array(g.source_type,g.source_id,g.cycle_id,g.owner_user_id,g.binding_version,g.source_version,g.due_on,g.guest_lifecycle_version)::text,'UTF8')),'hex')
 from guest g
 order by 1,2;
end $$;

create function private.get_care_reminder_readiness()
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare v_settings private.care_reminder_settings%rowtype;v_today date:=(statement_timestamp() at time zone 'America/Chicago')::date;v_counts jsonb;
begin
 if private.current_staff_role() is distinct from 'admin'::public.staff_role then raise exception 'CARE_REMINDER_ADMIN_REQUIRED' using errcode='42501';end if;
 select * into v_settings from private.care_reminder_settings where id;
 if not found then raise exception 'CARE_REMINDER_SETTINGS_MISSING' using errcode='55000';end if;
 select jsonb_build_object(
  'bindings',count(*),'enabled_bindings',count(*) filter(where b.enabled),
  'disabled_bindings',count(*) filter(where not b.enabled),
  'missing_sources',count(*) filter(where (b.source_type='care_plan' and p.id is null) or (b.source_type='guest_task' and (t.id is null or c.id is null))),
  'owner_changed',count(*) filter(where b.enabled and b.source_type='guest_task' and b.owner_user_id is distinct from t.assigned_staff_user_id),
  'lifecycle_changed',count(*) filter(where b.enabled and b.source_type='guest_task' and b.lifecycle_version is distinct from c.guest_lifecycle_version),
  'recipient_unavailable',count(*) filter(where b.enabled and b.owner_user_id is not null and not exists(select 1 from private.eligible_intake_staff() s where s.id=b.owner_user_id)),
  'unassigned',count(*) filter(where b.enabled and b.owner_user_id is null),
  'linked_welcome_suppressed',count(*) filter(where b.enabled and p.one_time and p.care_role='welcome' and exists(select 1 from public.app_submission_tasks linked
   join public.app_connections registration on registration.id=linked.registration_id where linked.id=b.linked_guest_task_id and linked.kind='guest_followup' and registration.contact_id=p.contact_id)),
  'linked_source_changed',count(*) filter(where b.enabled and b.linked_guest_task_id is not null and not exists(select 1 from public.app_submission_tasks linked
   join public.app_connections registration on registration.id=linked.registration_id where linked.id=b.linked_guest_task_id and linked.kind='guest_followup' and p.one_time and p.care_role='welcome' and registration.contact_id=p.contact_id)),
  'inactive_sources',count(*) filter(where b.enabled and ((p.id is not null and (p.paused or person.status='inactive')) or (t.id is not null and (t.status='completed' or t.guest_removed_at is not null or c.guest_removed_at is not null or c.status='archived'))))
 ) into v_counts from private.care_reminder_bindings b
 left join public.care_assignments p on b.source_type='care_plan' and p.id=b.source_id left join public.contacts person on person.id=p.contact_id
 left join public.app_submission_tasks t on b.source_type='guest_task' and t.id=b.source_id left join public.app_connections c on c.id=t.registration_id;
 v_counts:=v_counts||jsonb_build_object('open_sources',(select count(*) from private.care_reminder_source_rows(v_today)),
  'unbound_care',(select count(*) from public.care_assignments p join public.contacts c on c.id=p.contact_id where not p.paused and c.status in('active','visitor')
   and not(p.one_time and exists(select 1 from public.care_visits v where v.contact_id=p.contact_id and v.care_role=p.care_role and v.outcome='contacted' and v.contacted_on between p.started_on and v_today))
   and not exists(select 1 from private.care_reminder_bindings b where b.source_type='care_plan' and b.source_id=p.id)),
  'unbound_guests',(select count(*) from public.app_submission_tasks t join public.app_connections c on c.id=t.registration_id where t.kind='guest_followup' and t.status<>'completed' and t.guest_removed_at is null and c.guest_removed_at is null and c.status<>'archived' and not exists(select 1 from private.care_reminder_bindings b where b.source_type='guest_task' and b.source_id=t.id)));
 return jsonb_build_object('available',true,'version',1,'enabled',v_settings.enabled,'settings_version',v_settings.version,'today',v_today,'counts',v_counts,
  'pastor_setup_required',cardinality(v_settings.pastor_user_ids)=0 or exists(select 1 from unnest(v_settings.pastor_user_ids) u where not exists(select 1 from private.eligible_intake_staff() s where s.id=u)));
end $$;

create function private.get_care_reminder_settings()
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare v_settings private.care_reminder_settings%rowtype;v_bindings jsonb;
begin
 if private.current_staff_role() is distinct from 'admin'::public.staff_role then raise exception 'CARE_REMINDER_ADMIN_REQUIRED' using errcode='42501';end if;
 select * into v_settings from private.care_reminder_settings where id;
 if not found then raise exception 'CARE_REMINDER_SETTINGS_MISSING' using errcode='55000';end if;
 if (select count(*) from private.care_reminder_bindings)>5000 then raise exception 'CARE_REMINDER_SOURCE_LIMIT' using errcode='54000';end if;
 select coalesce(jsonb_agg(jsonb_build_object('source_type',b.source_type,'source_id',b.source_id,'owner_user_id',b.owner_user_id,'enabled',b.enabled,'cycle_id',b.cycle_id,
  'version',b.version,'approved_source_version',b.approved_source_version,'lifecycle_version',b.lifecycle_version,'linked_guest_task_id',b.linked_guest_task_id) order by b.source_type,b.source_id),'[]'::jsonb) into v_bindings from private.care_reminder_bindings b;
 return jsonb_build_object('version',1,'settings_version',v_settings.version,'enabled',v_settings.enabled,'pastor_user_ids',v_settings.pastor_user_ids,'bindings',v_bindings,
  'eligible_staff_user_ids',(select coalesce(jsonb_agg(s.id order by s.id),'[]'::jsonb) from private.eligible_intake_staff() s));
end $$;

create function public.get_care_reminder_settings() returns jsonb language sql stable security invoker set search_path='' as $$select private.get_care_reminder_settings()$$;
create function public.get_care_reminder_readiness() returns jsonb language sql stable security invoker set search_path='' as $$select private.get_care_reminder_readiness()$$;
create function public.set_care_reminder_settings(p_request_id uuid,p_version integer,p_enabled boolean,p_pastor_user_ids uuid[])
returns jsonb language sql security invoker set search_path='' as $$select private.set_care_reminder_settings(p_request_id,p_version,p_enabled,p_pastor_user_ids)$$;
create function public.set_care_reminder_binding(p_request_id uuid,p_source_type text,p_source_id uuid,p_version integer,p_source_version integer,p_owner_user_id uuid,p_enabled boolean,p_restart_cycle boolean,p_lifecycle_version integer,p_linked_guest_task_id uuid)
returns jsonb language sql security invoker set search_path='' as $$select private.set_care_reminder_binding(p_request_id,p_source_type,p_source_id,p_version,p_source_version,p_owner_user_id,p_enabled,p_restart_cycle,p_lifecycle_version,p_linked_guest_task_id)$$;
revoke all on function private.keep_care_reminder_config_receipt(),private.care_reminder_source_rows(date),private.get_care_reminder_settings(),private.get_care_reminder_readiness(),public.get_care_reminder_settings(),public.get_care_reminder_readiness(),
 private.set_care_reminder_settings(uuid,integer,boolean,uuid[]),public.set_care_reminder_settings(uuid,integer,boolean,uuid[]),
 private.set_care_reminder_binding(uuid,text,uuid,integer,integer,uuid,boolean,boolean,integer,uuid),public.set_care_reminder_binding(uuid,text,uuid,integer,integer,uuid,boolean,boolean,integer,uuid)
from public,anon,authenticated,service_role;
grant execute on function private.get_care_reminder_settings(),private.get_care_reminder_readiness(),public.get_care_reminder_settings(),public.get_care_reminder_readiness(),
 private.set_care_reminder_settings(uuid,integer,boolean,uuid[]),public.set_care_reminder_settings(uuid,integer,boolean,uuid[]),
 private.set_care_reminder_binding(uuid,text,uuid,integer,integer,uuid,boolean,boolean,integer,uuid),public.set_care_reminder_binding(uuid,text,uuid,integer,integer,uuid,boolean,boolean,integer,uuid)
to authenticated;
commit;
