-- Proposed infrastructure prerequisite; generated by Supabase CLI 2.117.0.
-- Review/apply separately from the functional SQL. No job or HTTP request here.
-- Official Supabase Cron install guide pins pg_catalog; pg_net maintains net objects.
-- https://supabase.com/docs/guides/cron/install
-- https://supabase.com/docs/guides/ai/automatic-embeddings
begin;
create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net with schema extensions;
commit;
